version: "3.9"

services:
  prometheus:
    image: akwizzy/prometheus-monitoring:latest
    container_name: prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - prometheus_data:/prometheus

    networks:
      - monitoring

volumes:
  prometheus_data:

networks:
  monitoring:
    external: true