version: "3.9"

services:

  prometheus:
    image: akwizzy/pilot-repo:prometheus
    container_name: prometheus
    restart: unless-stopped

    expose:
      - "9090"

    volumes:
      - prometheus_data:/prometheus

    networks:
      - monitoring

  grafana:
    image: akwizzy/pilot-repo:grafana
    container_name: grafana
    restart: unless-stopped

    expose:
      - "3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - loki

    networks:
      - monitoring
      - reverse-proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.grafana.rule=Host(`grafana.aktechnoservices.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"

      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}

      - GF_AUTH_GENERIC_OAUTH_ENABLED=${GF_AUTH_GENERIC_OAUTH_ENABLED}
      - GF_AUTH_GENERIC_OAUTH_NAME=${GF_AUTH_GENERIC_OAUTH_NAME}

      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}

      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=${GF_AUTH_GENERIC_OAUTH_AUTH_URL}
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${GF_AUTH_GENERIC_OAUTH_TOKEN_URL}
      - GF_AUTH_GENERIC_OAUTH_API_URL=${GF_AUTH_GENERIC_OAUTH_API_URL}

  loki:
    image: akwizzy/pilot-repo:loki
    container_name: loki
    restart: unless-stopped

    expose:
      - "3100"

    volumes:
      - loki_data:/loki

    networks:
      - monitoring

  alertmanager:
    image: akwizzy/pilot-repo:alertmanager
    container_name: alertmanager
    restart: unless-stopped

    expose:
      - "9093"
      
    volumes:
      - alertmanager_data:/alertmanager

    networks:
      - monitoring
      - reverse-proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.alerts.rule=Host(`alerts.aktechnoservices.com`)"
      - "traefik.http.routers.alerts.entrypoints=websecure"
      - "traefik.http.routers.alerts.tls.certresolver=letsencrypt"

      - "traefik.http.services.alerts.loadbalancer.server.port=9093"


  node-exporter:
    image: akwizzy/pilot-repo:node-exporter
    container_name: node-exporter
    restart: unless-stopped

    expose:
      - "9100"

    networks:
      - monitoring

  promtail:
    image: akwizzy/pilot-repo:promtail
    container_name: promtail

    restart: unless-stopped

    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - -config.file=/etc/promtail/config.yml

    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor

    restart: unless-stopped

    expose:
      - "8085:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

    privileged: true

    devices:
      - /dev/kmsg

    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  alertmanager_data:

networks:
  monitoring:
    external: true

  reverse-proxy:
    external: true